apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpp-workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: cpp-dev
spec:
  containers:
    - name: cpp-dev
      image: registry.access.redhat.com/ubi8/ubi
      command: ["sleep", "infinity"]
      securityContext:
        allowPrivilegeEscalation: true
        runAsUser: 0  # Run as root to allow dnf
      volumeMounts:
        - name: workspace
          mountPath: /opt/app-root/src/workspace
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: cpp-workspace-pvc
