apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  namespace: tme-obx
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: tme-obx.otel
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: opentelemetry
    operator.opentelemetry.io/collector-service-type: base
spec:
  endpoints:
    - interval: 5s
      port: prometheus
  namespaceSelector:
    matchNames:
      - tme-obx
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: tme-obx.otel
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/part-of: opentelemetry
      operator.opentelemetry.io/collector-service-type: base
