apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: ebpf-profiler-scc
allowHostPID: true
allowHostNetwork: true
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:open5gs-monitoring:default
