apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-collector
  namespace: open5gs-monitoring
spec:
  mode: deployment
  observability:
    metrics: {}
  deploymentUpdateStrategy: {}
  config:
    exporters:
      debug:
        verbosity: detailed
      prometheus:
        endpoint: '0.0.0.0:8889'
    processors:
      attributes:
        actions:
          - action: upsert
            key: collector.name
            value: otelcol-monitoring
      batch:
        send_batch_size: 1024
        timeout: 1s
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: '0.0.0.0:4317'
          http:
            endpoint: '0.0.0.0:4318'
    service:
      pipelines:
        metrics:
          exporters:
            - prometheus
            - debug
          processors:
            - batch
            - attributes
          receivers:
            - otlp
        traces:
          exporters:
            - debug
          processors:
            - batch
            - attributes
          receivers:
            - otlp
      telemetry:
        logs:
          development: true
          level: debug
        metrics:
          address: '0.0.0.0:8888'
  targetAllocator:
    allocationStrategy: consistent-hashing
    filterStrategy: relabel-config
    prometheusCR:
      scrapeInterval: 30s
  managementState: managed
  upgradeStrategy: automatic
  ingress:
    route: {}
  ipFamilyPolicy: SingleStack
