apiVersion: v1
kind: Service
metadata:
  name: otelcol-collector-metrics
  namespace: open5gs-monitoring
  labels:
    app.kubernetes.io/name: otelcol-collector-metrics
spec:
  ports:
  - name: metrics
    port: 8888
    protocol: TCP
    targetPort: 8889
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: open5gs-monitoring.otelcol-collector
    app.kubernetes.io/name: otelcol-collector-collector
