apiVersion: v1
kind: Service
metadata:
  name: otelcol-collector-metrics
  namespace: open5gs-monitoring
  labels:
    app.kubernetes.io/name: otelcol-collector
spec:
  ports:
  - name: metrics
    port: 8888
    targetPort: 8888
  - name: grpc
    port: 4317
    targetPort: 4317
  selector:
    app.kubernetes.io/name: otelcol-collector
