apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: open5gs-monitoring
spec:
  endpoints:
  - port: metrics
    interval: 10s
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
