apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  namespace: tme-aix02
spec:
  endpoints:
    - interval: 5s
      port: metrics
  namespaceSelector:
    matchNames:
      - tme-aix02
  selector:
    matchLabels:
      app: tme-aix-wb02
      service.name: fenar-app
