apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector-monitor
  namespace: tme-aix02
spec:
  endpoints:
    - interval: 5s
      port: prometheus
  namespaceSelector:
    matchNames:
      - tme-aix02
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: tme-aix02.otel-collector
      app.kubernetes.io/name: otel-collector-collector
      app.kubernetes.io/part-of: opentelemetry
      operator.opentelemetry.io/collector-service-type: base
